### ISSUE TITLE
testing-library/vue incompatible with nuxt-vitest?

### ISSUE THREAD

**Issue by danlourenco** [nuxt/nuxt-vitest#382]
Hello there! I've been trying to get `testing-library/vue` to work with a `nuxt-vitest` project to no avail. I receive the following error when I run my test:

```
TypeError: Cannot read properties of null (reading 'parentElement')
 ❯ VueWrapper.get node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7627:32
 ❯ Proxy.render node_modules/@testing-library/vue/dist/render.js:40:22
```

Here is a repo, if that is useful: https://stackblitz.com/edit/nuxt-starter-jvw52s?file=app.vue,app.spec.ts

Any ideas as to what may be going on here? Happy to provide any additional insight/assistance.

**Comment by oskarols** [comment]
Hi 👋 

Using `render` from `@testing-library/vue` won't work since it's not not in any way aware of the nuxt application. 

You should use [renderSuspended](https://github.com/danielroe/nuxt-vitest#rendersuspended) if you want to use testing-library.

**Comment by danlourenco** [comment]
Thank you for that info! I'll give that a shot.

**Comment by nathanchase** [comment]
@danlourenco You can extend vitest to support `testing-library` via https://github.com/testing-library/jest-dom#with-vitest
